name: Run Postman Collections

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  run-postman:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install Newman (Postman CLI)
        run: npm install -g newman

      - name: Run Assignment 2 collection
        run: newman run "Assignment-2.postman_collection.json"

      - name: Run Assignment 3 collection
        run: newman run "Assignment-3.postman_collection.json"

      - name: Run Assignment 4 collection
        run: newman run "Assignment-4.postman_collection.json"

      - name: Run Assignment 5 collection
        run: newman run "Assignment-5.postman_collection.json"
